pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
branches: master
