pipeline:
  build:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      dry_run: true
  push-latest:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
  push-release:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags: "${CI_REPO_TAG##v}" # strips v from the tag
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
      tag: v*
