pipeline:
  release:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      autotag: true
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
      tag: v*
