pipeline:
  release:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags:
        - "${CI_COMMIT_TAG##v}"
        - "latest"
    secrets: [docker_username, docker_password]
when:
  event: tag
  tag: v*
